name: Build and deploy JAR app to Azure Web App - postech-fiap-app1

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'


      - name: Find pom.xml
        run: |
          pwd
          ls -la
          echo "---- poms ----"
          find . -maxdepth 3 -name pom.xml -print

      - name: Build with Maven (complete/)
        working-directory: complete
        run: mvn -B -DskipTests clean package

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: complete/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'postech-fiap-app1'
          slot-name: 'Production'
          package: '*.jar'
