name: Java App Fiap Postech

on:
  push:
    branches:
      - main
      - developer
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven      
      
      - name: Build Initial with Maven
        working-directory: ./complete
        run: ./mvnw --batch-mode clean package
    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/complete/target/*.jar'        
